#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re, sys
from main import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())


# ./myseq -h
# ./myseq gcContent -h
# ./myseq countBases -h
# ./myseq enzTargetsScan -h
# ./myseq transcription -h
# ./myseq translation -h
# ./myseq transcription --seq ATGGGccGTAGAATTCTTGCaaGCCCGT
# ./myseq transcription --seq ATGGGccGTAGAATTCTTGCaaGCCCGT --revcomp
# ./myseq translation --seq ATGGGccGTAGAATTCTTGCaaGCCCGT
# ./myseq translation --seq ATGGGccGTAGAATTCTTGCaaGCCCGT --revcomp
# ./myseq gcContent --seq ATGGGccGTAGAATTCTTGCaaGCCCGT
# ./myseq countBases --seq ATGGGccGTAGAATTCTTGCaaGCCCGT
# ./myseq countBases --seq ATGGGccGTAGAATTCTTGCaaGCCCGT -r
# ./myseq enzTargetsScan --seq ATGGGccGTAGAATTCTTGCaaGCCCGT -e EcoRI
# ./myseq enzTargetsScan --seq ATGGGccGTAGAATTCTTGCaaGCCCGT -e EcoRI -r